SELECT t1.TABLE_NAME, t1.COLUMN_NAME, COLUMN_TYPE FROM
	(SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA='your_super-duper_fancy_database_name') t1
INNER JOIN
	(SELECT DISTINCT TABLE_NAME, COLUMN_NAME
	FROM INFORMATION_SCHEMA.STATISTICS
	WHERE TABLE_SCHEMA = 'your_super-duper_fancy_database_name') t2
ON t1.COLUMN_NAME=t2.COLUMN_NAME AND t1.TABLE_NAME=t2.TABLE_NAME
ORDER BY COLUMN_TYPE;
